#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login_check

# app/config/routing.yml or config/routes.yaml
gesdinet_jwt_refresh_token:
    path: /api/token/refresh
# ...